# Sample incidents seeded into an empty database at startup so the dashboard is not blank
# on a fresh deploy. Each account is written the way a real guard would write it: long
# (500+ words), professional in intent but with genuine spelling and grammar errors. The
# sets are built to exercise the report: real conflicts between accounts, near-duplicate
# wording that should NOT be flagged, and at least one dimension nobody covered. The
# "label" on each report is the guard's name; the conflicts section refers to that name.

SAMPLES = [
    {
        "title": "After-Hours Trespasser at East Loading Dock",
        "reports": [
            {
                "label": "Officer D. Reyes",
                "body": (
                    "On Tuesday March 4th at approxamitely 2305 hrs (11:05 PM) i was "
                    "conducting my regular perimiter patrol on the east side of the property "
                    "like i do most every night around that time. The weather was cold and a "
                    "little foggy wich made visability not great but i could still see ok with "
                    "my flashlite. I was walking the fence line near the east loading dock "
                    "when i noticied a male subject standing close to the roll up door, kind "
                    "of in between the dumpster enclosure and the dock itself. Right away i "
                    "thought this was strange because that dock gets secured and locked at "
                    "2000 hrs every night per the nightly check list, and i had personaly "
                    "checked it earlier in my shift and it was locked, so there was no reason "
                    "for anybody to be back there at that hour especialy someone with no badge "
                    "or vest on.\n\n"
                    "The subject was a white male, i would say around 5'10 to 6'0, medium "
                    "build, and he had on a dark colored hooded sweatshirt with the hood "
                    "pulled up over his head and dark jeans. I could not get a good look at "
                    "his face at all because of the hood and how dark it was back there. I "
                    "anounced myself in a loud clear voice and told him to stop and identify "
                    "himself and state his business on the property. He did not say nothing "
                    "back to me, instead he immediatley turned and started walking very fast "
                    "away from me towards the north fence line. At that point i radioed "
                    "dispatch at 2307 hrs to advise i had a unknown male and requested back up "
                    "to my location. I kept following him but i kept my distance like we are "
                    "trained because you dont approach alone, and i did not attempt to grab "
                    "him or make contact.\n\n"
                    "The subject got to the perimiter fence at the north east corner of the "
                    "lot and climbed straight over it, he droped down on the other side and "
                    "kept going north on foot away from the building. I want to note for the "
                    "record that i did NOT see him carrying anything in his hands the whole "
                    "time i had eyes on him, no bag no box nothing that i could see. After he "
                    "was gone i went back and re checked the dock door and the area around it "
                    "and the door was still secured and locked and i did not observe any signs "
                    "of forced entry or any property that looked like it was missing or moved "
                    "at that time.\n\n"
                    "I stayed at the scene and waited for Officer Patel to arrive and we "
                    "walked the fence line together to make sure he didnt drop anything or "
                    "double back. Nothing was located. I completed my incident log entry and "
                    "continued my shift after. In my opinion this guy was probly casing the "
                    "building but i cant say that for sure, im just writing down what i seen. "
                    "Thats everything i can recall at this time."
                ),
            },
            {
                "label": "Officer K. Patel",
                "body": (
                    "At about 2320 hrs on the night of March 4th i responded to a radio call "
                    "from Officer Reyes who advised he had a unidentifed person down by the "
                    "east loading dock and was requesting back up. I was posted at the main "
                    "gate at the time so i jumped in the patrol cart and headed over. Instead "
                    "of going straight to the dock i made the decision to drive around the "
                    "south side of the building to try and cut off the route towards the "
                    "public parking structure, because in my experiance thats usualy where "
                    "these people run too. By the time i got my cart into position and had a "
                    "clear view, the subject was allready up at the fence at the north east "
                    "corner of the property.\n\n"
                    "I had a decent line of sight from where i was even though it was dark. I "
                    "watched the male subject go up and over the fence, and i can say pretty "
                    "confidently that he had a dark colored back pack on him, he was carrying "
                    "it over one of his shoulders as he was climbing. After he came down on "
                    "the far side he did not go north, what i saw was him run straight across "
                    "the access road towards the public parking structure that is on the "
                    "opposite side of the street from us. He headed for the stairwell entrance "
                    "of that structure. I tryed to follow him on foot to the edge of our "
                    "property but i lost sight of him once he got inside and i did not pursue "
                    "off property per policy. I never made any contact with the subject and i "
                    "was not able to get a good look at his face either, mostly just the back "
                    "of him.\n\n"
                    "I want to be clear that what i saw is a little different then what Officer "
                    "Reyes is saying about the direction. From my angle he definately went "
                    "towards the parking structure across the street and not north, but it was "
                    "dark and we where looking from two diffrent positions so im just "
                    "reporting what i personaly observed from where i was at. Same goes for "
                    "the back pack, i know i seen a bag on his shoulder.\n\n"
                    "After i lost the subject i drove back around and met up with Officer "
                    "Reyes at the dock. Together we walked the whole fence line on our side "
                    "with our flash lites looking for any dropped items, foot prints, or "
                    "anything else of evidentary value and we did not locate anything. I agree "
                    "with Officer Reyes that the dock door was secure when we checked it, it "
                    "was still locked and i didnt see no damage to it. I did not personaly go "
                    "inside the dock or do a inventory of any property so i cant speak to "
                    "weather anything was taken from in there. I advised dispatch we lost the "
                    "subject and cleared the call, then went back to my post at the gate. "
                    "Thats all i got for my part."
                ),
            },
            {
                "label": "Officer S. Brennan",
                "body": (
                    "I was assigned to the camera room / CCTV monitoring for the over night "
                    "shift on March 4th. At around 2306 hrs i was doing my normal rotation "
                    "through the camera feeds when i caught some movement on the east dock "
                    "camera (camera 12). I observed what looked like a person in all dark "
                    "clothing standing near the roll up door of the east loading dock. I "
                    "radioed down to the floor right away to let the officers know i had a "
                    "subject visable on camera in that area so they would be aware and could "
                    "respond.\n\n"
                    "I tryed my best to keep the subject in frame and i was able to track him "
                    "across two diffrent camera zones as he moved away from the dock and "
                    "headed in the direction of the north east fence. The problem is the "
                    "camera that covers that fence corner (camera 15) has a partial blind spot "
                    "due to one of the exterior light fixtures being mounted right in the line "
                    "of view, it washes out part of the image and theres also a section the "
                    "camera just doesnt reach. So when the subject got right up to the fence i "
                    "lost him for a few seconds and i did NOT personaly see him actualy go "
                    "over the fence on camera, by the time the image came back he was allready "
                    "out of frame.\n\n"
                    "One thing i did notice that i think is worth putting in the report, "
                    "before he moved off from the dock the subject stopped for a moment right "
                    "at the base of the roll up door and it looked like he crouched down or "
                    "reached down towards the bottom of the door with his hands. I could not "
                    "tell what exactly he was doing down there, the image is just not clear "
                    "enough at that distance and lighting to say if he was trying the door or "
                    "messing with the lock or what. I just know he was down low at the door "
                    "for a couple seconds before he took off.\n\n"
                    "As far as weather he was carrying a bag or a back pack, honestly i could "
                    "not tell from the footage one way or the other. The resolution on that "
                    "older camera is not the best and his body was kind of turned away from me "
                    "most of the time, so i cant confirm or deny the back pack, i didnt get a "
                    "clear enough look. I also could not make out any facial features or really "
                    "anything that would help identify the guy other then dark hoodie and dark "
                    "pants wich is what the other officers said too.\n\n"
                    "After the subject was gone i went back through the recording and saved "
                    "the relevant clips from cameras 12 and 15 covering roughly 2304 to 2312 "
                    "hrs into the incident folder on the system and i noted down all the time "
                    "stamps for the file. I stayed on the cameras the rest of the shift and "
                    "did not observe the subject return to the property. Anything else needed "
                    "just let me know and i can pull the footage."
                ),
            },
        ],
    },
    {
        "title": "Level 2 Parking Garage Vehicle Break-In",
        "reports": [
            {
                "label": "Officer J. Alvarez",
                "body": (
                    "On Friday March 7th at approxamitely 1515 hrs (around 3:15 in the after "
                    "noon) i was conducting a foot patrol of the parking garage and was just "
                    "comming up the ramp onto Level 2 when a tenant flagged me down. The "
                    "tenant identifed herself as Ms. Coleman who works in the office suite on "
                    "the 4th floor, i recognize her as a regular tenant in the building. She "
                    "was pretty upset and she reported to me that someone had broke the "
                    "drivers side window of her vehicle, wich is a silver four door sedan, and "
                    "that a laptop bag had been taken out of the back seat of the car. She "
                    "said she had only been gone maybe a hour or so.\n\n"
                    "As i was walking up towards the vehicle with her i observed ONE "
                    "individual, a male, wearing a red base ball cap and a gray jacket, who "
                    "was running away from the area of her vehicle and heading towards the "
                    "north stair well of the garage. I called out for him to stop but he did "
                    "not comply, he kept running and went into the north stair well and i lost "
                    "sight of him. I made the decision not to leave the tenant and the scene "
                    "to chase him down into the stair well by myself, instead i got on the "
                    "radio and advised dispatch of the situation and gave a description of the "
                    "male i seen and the direction he was headed.\n\n"
                    "I then secured the immediate area around the vehicle. I asked Ms. Coleman "
                    "not to touch the broken glass or reach into the car so we didnt disturb "
                    "any potential evidence. There was alot of broken glass on the ground "
                    "right next to the drivers side door and you could see the window was "
                    "completly smashed in. The laptop bag she described was a black bag and "
                    "she said it had her personal lap top and some work documents inside of "
                    "it. I took down her initial statement, her contact information, and the "
                    "info on her vehicle.\n\n"
                    "I requested over the radio that dispatch contact the property manager to "
                    "respond to the scene, and i also advised the tenant that she would need "
                    "to file a report with the local police department for the theft of her "
                    "property since that is a criminal matter outside of our scope, and i "
                    "provided her the non emergency number. I stayed on scene with the vehicle "
                    "and the tenant the entire time untill the property manager arrived so the "
                    "scene wasnt left unattended. I want to note that i only ever seen the one "
                    "guy in the red cap by her car, i did not see anybody else running or "
                    "acting suspicious in that area when i came up the ramp. The property "
                    "manager arrived a short time later and took over coordinating with the "
                    "tenant. I completed my report and returned to my patrol. Thats everything "
                    "i personaly observed."
                ),
            },
            {
                "label": "Officer M. Whitfield",
                "body": (
                    "On March 7th i was assigned to work the security camera room for my "
                    "shift. At around 1510 hrs, wich was a few minutes before the vehicle "
                    "break in on Level 2 got reported over the radio, i was monitoring the "
                    "feeds and i noticed some activity on the Level 2 camera. What i observed "
                    "was TWO individuals, not one, standing real close together next to a "
                    "silver vehicle that was parked in the row near the elevator lobby on that "
                    "level. They where kind of huddled by the drivers side of the car wich is "
                    "what caught my attention in the first place.\n\n"
                    "One of the two individuals was wearing a light colored cap, like a tan or "
                    "white color is what it looked like to me on the monitor. I would not "
                    "describe it as red, but the camera color can be a little off sometimes so "
                    "im just saying what it appeared to be on my screen. I could not tell you "
                    "what the second person was wearing exactly, darker clothing i think. "
                    "After a few moments i watched both individuals move away from the vehicle "
                    "pretty quick and they left the area together by going down the south "
                    "stair well at the far end of Level 2, wich is the opposite end from the "
                    "elevators. I radioed Officer Alvarez right away to advise what i was "
                    "seeing on the camera and the direction they where going.\n\n"
                    "From the camera angle i had i was able to see that the drivers side "
                    "window of the silver vehicle appeared to be shattered and broke out. I "
                    "did not have a camera that gave me a clear look at either persons face, "
                    "the angle was more from above and behind and the image quality is not the "
                    "greatest, so i would not be able to identify either of them by there "
                    "face. I mostly could only go off of clothing and build and the one light "
                    "colored cap.\n\n"
                    "I made sure to save the footage covering from about 1505 hrs to 1520 hrs "
                    "from the Level 2 cameras into the incident folder so it can be reviewed "
                    "later, and i noted the time stamps for the file. I understand Officer "
                    "Alvarez reported seeing one male in a red cap going to the north stair "
                    "well. All i can say is what i seen on my screen was two people leaving "
                    "together towards the south stair well, so theres a bit of a diffrence "
                    "there that somebody should probly look into when they review the video. "
                    "It is possible there was more then one person involved and we each just "
                    "caught a diffrent part of it from where we where at. I continued "
                    "monitoring the cameras for the rest of my shift in case they came back "
                    "but i did not see them again. Let me know if the recordings are needed "
                    "for the report."
                ),
            },
        ],
    },
    {
        "title": "Third-Floor Fire Alarm Activation (Overnight)",
        "reports": [
            {
                "label": "Officer R. Donnelly",
                "body": (
                    "At 0240 hrs on Sunday March 9th the main fire alarm panel in the security "
                    "office went into alarm and the panel was indicating a activation from a "
                    "smoke detector located on the 3rd floor, east wing of the building. As "
                    "the responding officer i immediatley made my way up to the 3rd floor to "
                    "investigate the cause of the alarm per our emergency procedures. When i "
                    "got up there i did a walk through of the east wing checking the offices "
                    "and the common areas one by one.\n\n"
                    "I did not observe any visable smoke anywhere and i did not see any flames "
                    "or fire of any kind. However i will say that when i got near the 3rd "
                    "floor break room and kitchen area i did notice a faint burnt smell, kind "
                    "of like something had been over cooked or burnt in there. It was not real "
                    "strong but it was definately noticable to me in that part of the floor. I "
                    "could not locate the exact source of the smell, the microwave and the "
                    "toaster oven in the break room where both turned off and cool to the "
                    "touch when i checked them and nothing was visibly burning in there.\n\n"
                    "Per protocol i held my position on the floor and did not reset anything, "
                    "and i waited for the fire department to respond since your supposed to "
                    "let them be the ones to clear it. The fire department arrived on scene at "
                    "approxamitely 0255 hrs and i met them and escorted them up and advised "
                    "them of the burnt smell i had noticed by the kitchen. They conducted "
                    "there own sweep of the 3rd floor east wing with there equipment. They did "
                    "not find any active fire or any real source of smoke, they told me it was "
                    "possibly just some burnt food or maybe dust burning off a heating element "
                    "but they could not say for certain what set the detector off. They "
                    "cleared the building as safe at about 0320 hrs.\n\n"
                    "After the fire department gave the all clear and cleared us to do so, i "
                    "went and reset the fire alarm panel back in the security office and the "
                    "system went back to normal status with no further alarms for the rest of "
                    "the night. I made all the appropriate entries in the log including the "
                    "alarm time, the fire department arrival and clear times, and the burnt "
                    "smell i observed. My personal opinion is that the alarm was most likely "
                    "set off by something minor in the kitchen area but as i said the actual "
                    "cause was never confirmed by the fire department so im noting it as "
                    "undetermined. I would recommend maybe having the detector in that area "
                    "checked and the kitchen appliances looked at just to be safe going "
                    "forward. That is my account of the incident."
                ),
            },
            {
                "label": "Officer A. Kim",
                "body": (
                    "In the early morning hours of March 9th, i believe it was right around "
                    "0240, a fire alarm started going off and the panel was showing it was on "
                    "the 3rd floor. At the time the alarm activated i was down on the lower "
                    "floors of the building doing my rounds. As soon as i heard the alarm and "
                    "confirmed it on my radio i began doing a sweep of the building for any "
                    "occupants, because at that hour the main concern is making sure nobody is "
                    "still inside that needs to get out, thats the priority over anything "
                    "else.\n\n"
                    "During my sweep i located three (3) members of the over night cleaning "
                    "crew who where working in the building that night. They where spread out "
                    "between the 2nd and 3rd floors when i found them. I instructed all three "
                    "of them to stop what they where doing and i escorted them down the "
                    "stairs and out of the building to the designated muster point wich is out "
                    "in the front parking lot. Once we where outside i took a head count and i "
                    "accounted for all three of them by name and checked there names against "
                    "the after hours sign in sheet on my clip board to confirm everybody that "
                    "had signed in was now accounted for and outside, wich they all where.\n\n"
                    "We waited outside at the muster point untill the fire department finished "
                    "there inspection. The fire department checked the floor and advised that "
                    "they did not find anything burning and that the building was safe. After "
                    "we got the all clear i let the three cleaning crew members know they "
                    "where allowed to go back inside, and they went back in to collect there "
                    "equipment and finish up there work.\n\n"
                    "One thing i wanted to mention, while i was sweeping the lower floors and "
                    "the stairwells on my way up, i personaly did not notice any smell of "
                    "smoke or any burning smell at all on the floors that i went through. It "
                    "all seemed normal to me where i was at. I know thats something that "
                    "should be in the report so i am including it. I did not personaly go into "
                    "the 3rd floor break room area myself so i cant speak to that specific "
                    "spot, i was focused on getting the cleaning crew out and accounted for "
                    "first.\n\n"
                    "I stayed with the evacuated staff the whole time as there point of "
                    "contact so they knew what was going on and didnt wander off or go back in "
                    "early. There was no panic and everybody stayed calm. After everything was "
                    "cleared and everyone was back inside safely i returned to my normal "
                    "duties and made my log entry of the evacuation and the head count. No "
                    "injurys to anybody and everybody was accounted for the entire time. Thats "
                    "my report of what happened on my end of it."
                ),
            },
        ],
    },
]
